language: generic
sudo: required
services:
  - docker
before_install:
  - docker build -t harrymead/docker-react -f Dockerfile.dev .
script:
  - docker run -e CI=true harrymead/docker-react npm run test -- --coverage