FROM node:alpine
USER node
ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
ENV PATH=$PATH:/home/node/.npm-global/bin
WORKDIR '/home/node'
COPY --chown=node:node package.json .
RUN npm install
COPY --chown=node:node . .
CMD ["npm","run","start"]